services:
  caddy:
    image: caddy:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - backend

  postgres:
    image: postgres:13
    volumes:
      # Datenbank-Speicher (Server-Festplatte)
      - ./postgres-data:/var/lib/postgresql/data
      
      # Schema: Wird AUTOMATISCH ausgeführt beim ersten Start (weil im initdb.d Ordner)
      - ./db_init_schema/init_schema.sql:/docker-entrypoint-initdb.d/10-schema.sql
      
      # Alle Backup-Dateien & Skripte (Ordner-Mapping)
      # Bringt import_backups.sql UND die .dat Dateien auf einmal rein.
      - ./backups/venlab_backup_0530:/backups

  backend:
    build:
    image: ghcr.io/tgm-hit/insy5-informationssysteme-vue-pwa-pwa_mbauer_mdragne_dgernesch/backend:latest
    restart: always
    environment:
      # Begrenzt Java auf maximal 475MB RAM
      JAVA_TOOL_OPTIONS: "-Xms256m -Xmx475m"
      
      # Sicherheitshalber hier explizit definieren, falls das Merging fehlschlägt:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/${POSTGRES_DB}"
      SPRING_DATASOURCE_USERNAME: "${POSTGRES_USER}"
      SPRING_DATASOURCE_PASSWORD: "${POSTGRES_PASSWORD}"
      JWT_TOKEN: "${JWT_SECRET}"

  frontend:
    build:
    image: ghcr.io/tgm-hit/insy5-informationssysteme-vue-pwa-pwa_mbauer_mdragne_dgernesch/frontend:latest
    restart: always
    ports: []
    volumes: []

volumes:
  caddy_data:
  caddy_config: